version: "3.9"
volumes:
  explainegy_pg:
services:
  postgres:
    image: postgres:latest
    container_name: explainegy_postgres
    volumes:
      - explainegy_pg:/var/lib/postgresql/data
      - ./docker_data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: "exit 0"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: explainegy_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com #the username to login to pgadmin
      PGADMIN_DEFAULT_PASSWORD: admin # the password to login to pgadmin
    ports:
      - "5050:80"
    volumes:
      - ./docker_data/servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./docker_data/pgpass:/pgpass # passwords for the connections in this file
    depends_on:
      - "postgres"
