UI:
  Scrollbar: true
  Zoom: false
  Theme: default
  Language: en
  TimeZone: ""
Search:
  BatchSize: 0
Maps:
  Animate: 0
  Style: ""
Features:
  Account: true
  Advanced: false
  Albums: true
  Archive: true
  Delete: false
  Download: true
  Edit: true
  Estimates: false
  Favorites: true
  Files: true
  Folders: true
  Import: true
  Labels: false
  Library: false
  Logs: true
  Moments: false
  People: false
  Places: false
  Private: true
  Ratings: true
  Reactions: true
  Review: false
  Search: true
  Services: true
  Settings: true
  Share: true
  Upload: true
  Videos: true
Import:
  Path: /
  Move: false
Index:
  Path: /
  Convert: true
  Rescan: false
  SkipArchived: false
Stack:
  UUID: true
  Meta: true
  Name: false
Share:
  Title: ""
Download:
  Name: file
  Disabled: false
  Originals: true
  MediaRaw: false
  MediaSidecar: false
Templates:
  Default: index.gohtml
